version: '3.8'

networks:
  mynetwork:
    external: true

services:
  nginx:
    build: images/nginx
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html"
    networks:
      - mynetwork
  php:
    build: images/php
    volumes:
      - .:/var/www/html
    networks:
      - mynetwork
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'user'
    ports:
      - '5432:5432'
    networks:
      - mynetwork
  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: florian.pereira@treezor.com
        PGADMIN_DEFAULT_PASSWORD: 1234
        PGADMIN_LISTEN_PORT: 80
      ports:
        - '15432:80'
      networks:
        - mynetwork
#      volumes:
#        - pgadmin:/var/lib/pgadmin
#      networks:
#        - postgres

#    volumes:
#      - db-data:/var/lib/postgresql/data:rw
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'db'
##       So you don't have to use root, but you can if you like
#     MYSQL_USER: 'user'
##       You can use whatever password you like
#      MYSQL_PASSWORD: '0000'
##       Password for root access
#      MYSQL_ROOT_PASSWORD: '1234'
#    ports:
##       <Port exposed> : < MySQL Port running inside container>
#      - '3306:3306'
##    expose:
##       Opens port 3306 on the container
##      - '3306'
#    volumes:
#      - mysql:/var/lib/mysql
#  phpmyadmin:
#    image: phpmyadmin
##    restart: always
#    ports:
#      - 8081:80
##    environment:
##      - PMA_ARBITRARY=1
#
volumes:
  db-data:
#  mysql:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '/Users/fp/Documents/Dev/Template/mySQL'

#